language: node_js   #前端工程所以是JavaScript，编译环境是node_js
node_js:
- '10'   #指定node版本
branchs:
  only:
    - master  #指定只有检测到master分支有变动时才执行任务
stages:
- deploy
# jobs:
#  include:
#   - stage: test
#     script:
#     - ls
#   -stage: deploy
#    script:
#     - npm version

deploy:
  provider: npm
  email: 13436281755@163.com
  api_key: "$NPM_TOKEN"
  skip_cleanup: true
  on:
    all_branches: true